// Locals
import type { AgentList } from './types'

const agentNames = [
  'Arnold Alexander',
  'Betty Brown',
  'Charlie Clark',
  'Diana Davis',
  'Edward Evans',
  'Fiona Foster',
  'George Green',
  'Hannah Harris',
  'Ian Irving',
  'Julia Jones',
  'Kevin King',
  'Laura Lee',
  'Michael Miller',
  'Nina Nelson',
  'Oscar Owens',
  'Paula Parker',
  'Quentin Quinn',
  'Rachel Reed',
  'Samuel Scott',
  'Tina Turner',
  'Uma Underwood',
  'Victor Vaughn',
  'Wendy White',
  'Xander Xu',
  'Yara Young',
  'Zane Zimmerman',
  'Ava Adams',
  'Brian Baker',
  'Cathy Carter',
  'David Dawson',
  'Ella Edwards',
  'Franklin Fisher',
  'Grace Grant',
  'Henry Hughes',
  'Isla Ingram',
  'Jack Johnson',
  'Kylie Knight',
  'Liam Lewis',
  'Mia Mitchell',
  'Noah Nichols',
  'Olivia Olsen',
  'Peter Price',
  'Queen Quill',
  'Ryan Ross',
  'Sophie Smith',
  'Thomas Taylor',
  'Ursula Underhill',
  'Violet Vaughn',
  'Willow West',
  'Xenia Xavier',
  'Yusuf Yates',
  'Zoey Zimmerman',
  'Amber Allen',
  'Blake Brooks',
  'Chloe Cooper',
  'Derek Daniels',
  'Eva Ellis',
  'Finn Ford',
  'Gabriella Gray',
  'Harvey Hill',
  'Isabel Irwin',
  'Jake Jenkins',
  'Kara Kelly',
  'Leo Lane',
  'Megan Moore',
  'Nathan Norris',
  'Olga Ortega',
  'Paul Peterson',
  'Quincy Quick',
  'Riley Rivers',
  'Sara Sanders',
  'Tyler Thompson',
  'Ulysses Underwood',
  'Vera Vaughn',
  'Wesley Wood',
  'Ximena Xanders',
  'Yosef Young',
  'Zara Zane',
  'Aiden Avery',
  'Brooke Benson',
  'Caleb Carter',
  'Delilah Dean',
  'Ethan Ellis',
  'Faith Foster',
  'Gavin Grant',
  'Hailey Hayes',
  'Isaac Innes',
  'Jasmine James',
  'Kyle Kim',
  'Lily Lane',
  'Mason Moore',
  'Natalie Nash',
  'Owen Oliver',
  'Piper Pierce',
  'Quinn Queen',
  'Ruby Reed',
  'Sebastian Stone',
  'Trinity Tate',
  'Uriel Underwood',
  'Valerie Vaughn',
]

export const mockAgents: AgentList = Array.from({ length: 40 }, (_, i) => ({
  id: (i + 1).toString(),
  name: agentNames[i % agentNames.length],
  image: {
    src: '/agent.webp',
    width: 295,
    height: 240,
    alt: agentNames[i % agentNames.length],
  },
  listings: Math.floor(Math.random() * 200) + 1,
}))
