import type { PropertyList } from './types'

export const mockPopularProperties: PropertyList = [
  {
    id: '1',
    title: 'Classic Damara',
    image: {
      src: '/property.webp',
      width: 295,
      height: 240,
      alt: 'Classic Damara',
    },
    price: 480500,
    location: 'Seattle, United States',
    beds: 4,
    baths: 2,
    sqft: 2845,
  },
  {
    id: '2',
    title: 'Modern Villa',
    image: {
      src: '/property.webp',
      width: 295,
      height: 240,
      alt: 'Modern Villa',
    },
    price: 750000,
    location: 'Los Angeles, United States',
    beds: 5,
    baths: 3,
    sqft: 3534,
  },
  {
    id: '3',
    title: 'Urban Apartment',
    image: {
      src: '/property.webp',
      width: 295,
      height: 240,
      alt: 'Urban Apartment',
    },
    price: 300000,
    location: 'New York, United States',
    beds: 2,
    baths: 1,
    sqft: 1223,
  },
  {
    id: '4',
    title: 'Cozy Cottage',
    image: {
      src: '/property.webp',
      width: 295,
      height: 240,
      alt: 'Cozy Cottage',
    },
    price: 200000,
    location: 'Portland, United States',
    beds: 3,
    baths: 2,
    sqft: 1521,
  },
  {
    id: '5',
    title: 'Luxury Estate',
    image: {
      src: '/property.webp',
      width: 295,
      height: 240,
      alt: 'Luxury Estate',
    },
    price: 1200000,
    location: 'Miami, United States',
    beds: 6,
    baths: 4,
    sqft: 5344,
  },
  {
    id: '6',
    title: 'Suburban Home',
    image: {
      src: '/property.webp',
      width: 295,
      height: 240,
      alt: 'Suburban Home',
    },
    price: 450000,
    location: 'San Francisco, United States',
    beds: 4,
    baths: 2,
    sqft: 2919,
  },
]
